name: Build Windows

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - run: npm run build-win64

      - uses: actions/upload-artifact@v4
        with:
          name: byuh-transcript-screener-windows
          path: |
            dist/*.exe
